- name: Creating the Directories required for prometheus 
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items: 
      - "{{ prometheus_configuration_directory }}"
      - "{{ prometheus_archive_file_download_directory }}"

- name: Downloading the prometheus archive file
  get_url: 
   url: "{{ prometheus_download_url }}" 
   dest: "{{ prometheus_archive_file_download_directory }}"
   owner: root
   group: root

- name: Extracting the prometheus archive file
  unarchive: 
   src: "{{ prometheus_archive_file_download_directory }}/{{ prometheus_archive_file_name }}"
   dest: "{{ prometheus_archive_file_download_directory }}"
   owner: root
   group: root
   remote_src: yes

- name: Copying the prometheus binary to /usr/local/bin
  copy: 
    src: "{{ prometheus_archive_file_download_directory }}/{{ prometheus_folder_name  }}/{{ prometheus_binary_name }}"
    dest: "{{ prometheus_binary_location }}/{{ prometheus_binary_name }}"
    owner: root
    group: root
    mode: 111
    remote_src: yes

- name: Copying the prometheus configuration file 
  copy: 
    src: "config/prometheus.yml"
    dest: "{{ prometheus_configuration_directory }}/prometheus.yml"
    owner: root
    group: root
  notify: 
  - Prometheus Service Restart

- name: Copying the systemd file for prometheus 
  template: 
    src: "systemd/system/prometheus.service.j2"
    dest: "/etc/systemd/system/{{ prometheus_service_name }}.service"
    owner: root
    group: root
  notify: 
   - Systemd Daemon Reload

- name: Start and enable the prometheus service
  service:
    name: "{{ prometheus_service_name }}"
    enabled: true
    state: started
